#!/bin/bash

# Manual deployment steps for VPS
echo "=== MANUAL DEPLOYMENT STEPS ==="
echo ""
echo "1. Upload marchabrasil-complete.tar.gz to your VPS /tmp/ directory"
echo ""
echo "2. SSH into your VPS:"
echo "   ssh root@148.230.85.210"
echo "   Password: Helena3266##"
echo ""
echo "3. Run these commands on the VPS:"
echo ""
echo "cd /var/www"
echo "rm -rf marchabrasil"
echo "mkdir marchabrasil"
echo "cd marchabrasil"
echo "tar -xzf /tmp/marchabrasil-complete.tar.gz"
echo "npm install --production"
echo "pm2 stop marchabrasil 2>/dev/null || true"
echo "pm2 delete marchabrasil 2>/dev/null || true"
echo "pm2 start server.js --name marchabrasil"
echo "pm2 save"
echo ""
echo "4. Access your platform at: http://148.230.85.210:3000"